/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DevicesRouteRouteImport } from './routes/devices/route'
import { Route as CabinetRouteRouteImport } from './routes/cabinet/route'
import { Route as DevicesIndexRouteImport } from './routes/devices/index'
import { Route as CabinetIndexRouteImport } from './routes/cabinet/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DevicesOauthCallbackRouteImport } from './routes/devices/oauth-callback'
import { Route as DevicesLoginRouteImport } from './routes/devices/login'
import { Route as CabinetTrashRouteImport } from './routes/cabinet/trash'
import { Route as CabinetTasksRouteImport } from './routes/cabinet/tasks'
import { Route as CabinetSharedRouteImport } from './routes/cabinet/shared'
import { Route as CabinetSettingsRouteImport } from './routes/cabinet/settings'
import { Route as CabinetSearchRouteImport } from './routes/cabinet/search'
import { Route as CabinetEncryptedRouteImport } from './routes/cabinet/encrypted'
import { Route as PublicTroubleshootingRouteImport } from './routes/_public/troubleshooting'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as CabinetFilesRouteRouteImport } from './routes/cabinet/files/route'
import { Route as CabinetDocsRouteRouteImport } from './routes/cabinet/docs/route'
import { Route as CabinetFilesIndexRouteImport } from './routes/cabinet/files/index'
import { Route as CabinetDocsIndexRouteImport } from './routes/cabinet/docs/index'
import { Route as PublicDocsIndexRouteImport } from './routes/_public/docs/index'
import { Route as DevicesPairRequestRouteImport } from './routes/devices/pair.request'
import { Route as DevicesPairAcceptRouteImport } from './routes/devices/pair.accept'
import { Route as CabinetWorkspaceSettingsRkeyRouteImport } from './routes/cabinet/workspace-settings/$rkey'
import { Route as CabinetFilesSplatRouteImport } from './routes/cabinet/files/$'
import { Route as CabinetEditorNewRouteImport } from './routes/cabinet/editor/new'
import { Route as CabinetEditorRkeyRouteImport } from './routes/cabinet/editor/$rkey'
import { Route as CabinetDocsSlugRouteImport } from './routes/cabinet/docs/$slug'
import { Route as PublicDocsSlugRouteImport } from './routes/_public/docs/$slug'
import { Route as CabinetWorkspaceRkeyRouteRouteImport } from './routes/cabinet/workspace/$rkey/route'
import { Route as CabinetWorkspaceRkeyIndexRouteImport } from './routes/cabinet/workspace/$rkey/index'
import { Route as CabinetWorkspaceRkeySplatRouteImport } from './routes/cabinet/workspace/$rkey/$'
import { Route as CabinetWorkspaceEditorRkeyNewRouteImport } from './routes/cabinet/workspace-editor/$rkey/new'
import { Route as CabinetWorkspaceEditorRkeyDocRkeyRouteImport } from './routes/cabinet/workspace-editor/$rkey/$docRkey'

const DevicesCliCallbackLazyRouteImport = createFileRoute(
  '/devices/cli-callback',
)()

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRouteRoute = DevicesRouteRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/devices/route.lazy').then((d) => d.Route))
const CabinetRouteRoute = CabinetRouteRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cabinet/route.lazy').then((d) => d.Route))
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRouteRoute,
} as any).lazy(() => import('./routes/devices/index.lazy').then((d) => d.Route))
const CabinetIndexRoute = CabinetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DevicesCliCallbackLazyRoute = DevicesCliCallbackLazyRouteImport.update({
  id: '/cli-callback',
  path: '/cli-callback',
  getParentRoute: () => DevicesRouteRoute,
} as any).lazy(() =>
  import('./routes/devices/cli-callback.lazy').then((d) => d.Route),
)
const DevicesOauthCallbackRoute = DevicesOauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => DevicesRouteRoute,
} as any).lazy(() =>
  import('./routes/devices/oauth-callback.lazy').then((d) => d.Route),
)
const DevicesLoginRoute = DevicesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DevicesRouteRoute,
} as any).lazy(() => import('./routes/devices/login.lazy').then((d) => d.Route))
const CabinetTrashRoute = CabinetTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() => import('./routes/cabinet/trash.lazy').then((d) => d.Route))
const CabinetTasksRoute = CabinetTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() => import('./routes/cabinet/tasks.lazy').then((d) => d.Route))
const CabinetSharedRoute = CabinetSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/shared.lazy').then((d) => d.Route),
)
const CabinetSettingsRoute = CabinetSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/settings.lazy').then((d) => d.Route),
)
const CabinetSearchRoute = CabinetSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/search.lazy').then((d) => d.Route),
)
const CabinetEncryptedRoute = CabinetEncryptedRouteImport.update({
  id: '/encrypted',
  path: '/encrypted',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/encrypted.lazy').then((d) => d.Route),
)
const PublicTroubleshootingRoute = PublicTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const CabinetFilesRouteRoute = CabinetFilesRouteRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/files/route.lazy').then((d) => d.Route),
)
const CabinetDocsRouteRoute = CabinetDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/docs/route.lazy').then((d) => d.Route),
)
const CabinetFilesIndexRoute = CabinetFilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CabinetFilesRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/files/index.lazy').then((d) => d.Route),
)
const CabinetDocsIndexRoute = CabinetDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CabinetDocsRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/docs/index.lazy').then((d) => d.Route),
)
const PublicDocsIndexRoute = PublicDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => PublicRoute,
} as any)
const DevicesPairRequestRoute = DevicesPairRequestRouteImport.update({
  id: '/pair/request',
  path: '/pair/request',
  getParentRoute: () => DevicesRouteRoute,
} as any).lazy(() =>
  import('./routes/devices/pair.request.lazy').then((d) => d.Route),
)
const DevicesPairAcceptRoute = DevicesPairAcceptRouteImport.update({
  id: '/pair/accept',
  path: '/pair/accept',
  getParentRoute: () => DevicesRouteRoute,
} as any).lazy(() =>
  import('./routes/devices/pair.accept.lazy').then((d) => d.Route),
)
const CabinetWorkspaceSettingsRkeyRoute =
  CabinetWorkspaceSettingsRkeyRouteImport.update({
    id: '/workspace-settings/$rkey',
    path: '/workspace-settings/$rkey',
    getParentRoute: () => CabinetRouteRoute,
  } as any)
const CabinetFilesSplatRoute = CabinetFilesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CabinetFilesRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/files/$.lazy').then((d) => d.Route),
)
const CabinetEditorNewRoute = CabinetEditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/editor/new.lazy').then((d) => d.Route),
)
const CabinetEditorRkeyRoute = CabinetEditorRkeyRouteImport.update({
  id: '/editor/$rkey',
  path: '/editor/$rkey',
  getParentRoute: () => CabinetRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/editor/$rkey.lazy').then((d) => d.Route),
)
const CabinetDocsSlugRoute = CabinetDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CabinetDocsRouteRoute,
} as any).lazy(() =>
  import('./routes/cabinet/docs/$slug.lazy').then((d) => d.Route),
)
const PublicDocsSlugRoute = PublicDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const CabinetWorkspaceRkeyRouteRoute =
  CabinetWorkspaceRkeyRouteRouteImport.update({
    id: '/workspace/$rkey',
    path: '/workspace/$rkey',
    getParentRoute: () => CabinetRouteRoute,
  } as any).lazy(() =>
    import('./routes/cabinet/workspace/$rkey/route.lazy').then((d) => d.Route),
  )
const CabinetWorkspaceRkeyIndexRoute =
  CabinetWorkspaceRkeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CabinetWorkspaceRkeyRouteRoute,
  } as any).lazy(() =>
    import('./routes/cabinet/workspace/$rkey/index.lazy').then((d) => d.Route),
  )
const CabinetWorkspaceRkeySplatRoute =
  CabinetWorkspaceRkeySplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => CabinetWorkspaceRkeyRouteRoute,
  } as any).lazy(() =>
    import('./routes/cabinet/workspace/$rkey/$.lazy').then((d) => d.Route),
  )
const CabinetWorkspaceEditorRkeyNewRoute =
  CabinetWorkspaceEditorRkeyNewRouteImport.update({
    id: '/workspace-editor/$rkey/new',
    path: '/workspace-editor/$rkey/new',
    getParentRoute: () => CabinetRouteRoute,
  } as any)
const CabinetWorkspaceEditorRkeyDocRkeyRoute =
  CabinetWorkspaceEditorRkeyDocRkeyRouteImport.update({
    id: '/workspace-editor/$rkey/$docRkey',
    path: '/workspace-editor/$rkey/$docRkey',
    getParentRoute: () => CabinetRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/cabinet': typeof CabinetRouteRouteWithChildren
  '/devices': typeof DevicesRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/cabinet/docs': typeof CabinetDocsRouteRouteWithChildren
  '/cabinet/files': typeof CabinetFilesRouteRouteWithChildren
  '/faq': typeof PublicFaqRoute
  '/troubleshooting': typeof PublicTroubleshootingRoute
  '/cabinet/encrypted': typeof CabinetEncryptedRoute
  '/cabinet/search': typeof CabinetSearchRoute
  '/cabinet/settings': typeof CabinetSettingsRoute
  '/cabinet/shared': typeof CabinetSharedRoute
  '/cabinet/tasks': typeof CabinetTasksRoute
  '/cabinet/trash': typeof CabinetTrashRoute
  '/devices/login': typeof DevicesLoginRoute
  '/devices/oauth-callback': typeof DevicesOauthCallbackRoute
  '/devices/cli-callback': typeof DevicesCliCallbackLazyRoute
  '/cabinet/': typeof CabinetIndexRoute
  '/devices/': typeof DevicesIndexRoute
  '/cabinet/workspace/$rkey': typeof CabinetWorkspaceRkeyRouteRouteWithChildren
  '/docs/$slug': typeof PublicDocsSlugRoute
  '/cabinet/docs/$slug': typeof CabinetDocsSlugRoute
  '/cabinet/editor/$rkey': typeof CabinetEditorRkeyRoute
  '/cabinet/editor/new': typeof CabinetEditorNewRoute
  '/cabinet/files/$': typeof CabinetFilesSplatRoute
  '/cabinet/workspace-settings/$rkey': typeof CabinetWorkspaceSettingsRkeyRoute
  '/devices/pair/accept': typeof DevicesPairAcceptRoute
  '/devices/pair/request': typeof DevicesPairRequestRoute
  '/docs/': typeof PublicDocsIndexRoute
  '/cabinet/docs/': typeof CabinetDocsIndexRoute
  '/cabinet/files/': typeof CabinetFilesIndexRoute
  '/cabinet/workspace-editor/$rkey/$docRkey': typeof CabinetWorkspaceEditorRkeyDocRkeyRoute
  '/cabinet/workspace-editor/$rkey/new': typeof CabinetWorkspaceEditorRkeyNewRoute
  '/cabinet/workspace/$rkey/$': typeof CabinetWorkspaceRkeySplatRoute
  '/cabinet/workspace/$rkey/': typeof CabinetWorkspaceRkeyIndexRoute
}
export interface FileRoutesByTo {
  '/faq': typeof PublicFaqRoute
  '/troubleshooting': typeof PublicTroubleshootingRoute
  '/cabinet/encrypted': typeof CabinetEncryptedRoute
  '/cabinet/search': typeof CabinetSearchRoute
  '/cabinet/settings': typeof CabinetSettingsRoute
  '/cabinet/shared': typeof CabinetSharedRoute
  '/cabinet/tasks': typeof CabinetTasksRoute
  '/cabinet/trash': typeof CabinetTrashRoute
  '/devices/login': typeof DevicesLoginRoute
  '/devices/oauth-callback': typeof DevicesOauthCallbackRoute
  '/devices/cli-callback': typeof DevicesCliCallbackLazyRoute
  '/': typeof PublicIndexRoute
  '/cabinet': typeof CabinetIndexRoute
  '/devices': typeof DevicesIndexRoute
  '/docs/$slug': typeof PublicDocsSlugRoute
  '/cabinet/docs/$slug': typeof CabinetDocsSlugRoute
  '/cabinet/editor/$rkey': typeof CabinetEditorRkeyRoute
  '/cabinet/editor/new': typeof CabinetEditorNewRoute
  '/cabinet/files/$': typeof CabinetFilesSplatRoute
  '/cabinet/workspace-settings/$rkey': typeof CabinetWorkspaceSettingsRkeyRoute
  '/devices/pair/accept': typeof DevicesPairAcceptRoute
  '/devices/pair/request': typeof DevicesPairRequestRoute
  '/docs': typeof PublicDocsIndexRoute
  '/cabinet/docs': typeof CabinetDocsIndexRoute
  '/cabinet/files': typeof CabinetFilesIndexRoute
  '/cabinet/workspace-editor/$rkey/$docRkey': typeof CabinetWorkspaceEditorRkeyDocRkeyRoute
  '/cabinet/workspace-editor/$rkey/new': typeof CabinetWorkspaceEditorRkeyNewRoute
  '/cabinet/workspace/$rkey/$': typeof CabinetWorkspaceRkeySplatRoute
  '/cabinet/workspace/$rkey': typeof CabinetWorkspaceRkeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/cabinet': typeof CabinetRouteRouteWithChildren
  '/devices': typeof DevicesRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/cabinet/docs': typeof CabinetDocsRouteRouteWithChildren
  '/cabinet/files': typeof CabinetFilesRouteRouteWithChildren
  '/_public/faq': typeof PublicFaqRoute
  '/_public/troubleshooting': typeof PublicTroubleshootingRoute
  '/cabinet/encrypted': typeof CabinetEncryptedRoute
  '/cabinet/search': typeof CabinetSearchRoute
  '/cabinet/settings': typeof CabinetSettingsRoute
  '/cabinet/shared': typeof CabinetSharedRoute
  '/cabinet/tasks': typeof CabinetTasksRoute
  '/cabinet/trash': typeof CabinetTrashRoute
  '/devices/login': typeof DevicesLoginRoute
  '/devices/oauth-callback': typeof DevicesOauthCallbackRoute
  '/devices/cli-callback': typeof DevicesCliCallbackLazyRoute
  '/_public/': typeof PublicIndexRoute
  '/cabinet/': typeof CabinetIndexRoute
  '/devices/': typeof DevicesIndexRoute
  '/cabinet/workspace/$rkey': typeof CabinetWorkspaceRkeyRouteRouteWithChildren
  '/_public/docs/$slug': typeof PublicDocsSlugRoute
  '/cabinet/docs/$slug': typeof CabinetDocsSlugRoute
  '/cabinet/editor/$rkey': typeof CabinetEditorRkeyRoute
  '/cabinet/editor/new': typeof CabinetEditorNewRoute
  '/cabinet/files/$': typeof CabinetFilesSplatRoute
  '/cabinet/workspace-settings/$rkey': typeof CabinetWorkspaceSettingsRkeyRoute
  '/devices/pair/accept': typeof DevicesPairAcceptRoute
  '/devices/pair/request': typeof DevicesPairRequestRoute
  '/_public/docs/': typeof PublicDocsIndexRoute
  '/cabinet/docs/': typeof CabinetDocsIndexRoute
  '/cabinet/files/': typeof CabinetFilesIndexRoute
  '/cabinet/workspace-editor/$rkey/$docRkey': typeof CabinetWorkspaceEditorRkeyDocRkeyRoute
  '/cabinet/workspace-editor/$rkey/new': typeof CabinetWorkspaceEditorRkeyNewRoute
  '/cabinet/workspace/$rkey/$': typeof CabinetWorkspaceRkeySplatRoute
  '/cabinet/workspace/$rkey/': typeof CabinetWorkspaceRkeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cabinet'
    | '/devices'
    | '/'
    | '/cabinet/docs'
    | '/cabinet/files'
    | '/faq'
    | '/troubleshooting'
    | '/cabinet/encrypted'
    | '/cabinet/search'
    | '/cabinet/settings'
    | '/cabinet/shared'
    | '/cabinet/tasks'
    | '/cabinet/trash'
    | '/devices/login'
    | '/devices/oauth-callback'
    | '/devices/cli-callback'
    | '/cabinet/'
    | '/devices/'
    | '/cabinet/workspace/$rkey'
    | '/docs/$slug'
    | '/cabinet/docs/$slug'
    | '/cabinet/editor/$rkey'
    | '/cabinet/editor/new'
    | '/cabinet/files/$'
    | '/cabinet/workspace-settings/$rkey'
    | '/devices/pair/accept'
    | '/devices/pair/request'
    | '/docs/'
    | '/cabinet/docs/'
    | '/cabinet/files/'
    | '/cabinet/workspace-editor/$rkey/$docRkey'
    | '/cabinet/workspace-editor/$rkey/new'
    | '/cabinet/workspace/$rkey/$'
    | '/cabinet/workspace/$rkey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/faq'
    | '/troubleshooting'
    | '/cabinet/encrypted'
    | '/cabinet/search'
    | '/cabinet/settings'
    | '/cabinet/shared'
    | '/cabinet/tasks'
    | '/cabinet/trash'
    | '/devices/login'
    | '/devices/oauth-callback'
    | '/devices/cli-callback'
    | '/'
    | '/cabinet'
    | '/devices'
    | '/docs/$slug'
    | '/cabinet/docs/$slug'
    | '/cabinet/editor/$rkey'
    | '/cabinet/editor/new'
    | '/cabinet/files/$'
    | '/cabinet/workspace-settings/$rkey'
    | '/devices/pair/accept'
    | '/devices/pair/request'
    | '/docs'
    | '/cabinet/docs'
    | '/cabinet/files'
    | '/cabinet/workspace-editor/$rkey/$docRkey'
    | '/cabinet/workspace-editor/$rkey/new'
    | '/cabinet/workspace/$rkey/$'
    | '/cabinet/workspace/$rkey'
  id:
    | '__root__'
    | '/cabinet'
    | '/devices'
    | '/_public'
    | '/cabinet/docs'
    | '/cabinet/files'
    | '/_public/faq'
    | '/_public/troubleshooting'
    | '/cabinet/encrypted'
    | '/cabinet/search'
    | '/cabinet/settings'
    | '/cabinet/shared'
    | '/cabinet/tasks'
    | '/cabinet/trash'
    | '/devices/login'
    | '/devices/oauth-callback'
    | '/devices/cli-callback'
    | '/_public/'
    | '/cabinet/'
    | '/devices/'
    | '/cabinet/workspace/$rkey'
    | '/_public/docs/$slug'
    | '/cabinet/docs/$slug'
    | '/cabinet/editor/$rkey'
    | '/cabinet/editor/new'
    | '/cabinet/files/$'
    | '/cabinet/workspace-settings/$rkey'
    | '/devices/pair/accept'
    | '/devices/pair/request'
    | '/_public/docs/'
    | '/cabinet/docs/'
    | '/cabinet/files/'
    | '/cabinet/workspace-editor/$rkey/$docRkey'
    | '/cabinet/workspace-editor/$rkey/new'
    | '/cabinet/workspace/$rkey/$'
    | '/cabinet/workspace/$rkey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CabinetRouteRoute: typeof CabinetRouteRouteWithChildren
  DevicesRouteRoute: typeof DevicesRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/cabinet/': {
      id: '/cabinet/'
      path: '/'
      fullPath: '/cabinet/'
      preLoaderRoute: typeof CabinetIndexRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/devices/cli-callback': {
      id: '/devices/cli-callback'
      path: '/cli-callback'
      fullPath: '/devices/cli-callback'
      preLoaderRoute: typeof DevicesCliCallbackLazyRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/oauth-callback': {
      id: '/devices/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/devices/oauth-callback'
      preLoaderRoute: typeof DevicesOauthCallbackRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/login': {
      id: '/devices/login'
      path: '/login'
      fullPath: '/devices/login'
      preLoaderRoute: typeof DevicesLoginRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/cabinet/trash': {
      id: '/cabinet/trash'
      path: '/trash'
      fullPath: '/cabinet/trash'
      preLoaderRoute: typeof CabinetTrashRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/tasks': {
      id: '/cabinet/tasks'
      path: '/tasks'
      fullPath: '/cabinet/tasks'
      preLoaderRoute: typeof CabinetTasksRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/shared': {
      id: '/cabinet/shared'
      path: '/shared'
      fullPath: '/cabinet/shared'
      preLoaderRoute: typeof CabinetSharedRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/settings': {
      id: '/cabinet/settings'
      path: '/settings'
      fullPath: '/cabinet/settings'
      preLoaderRoute: typeof CabinetSettingsRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/search': {
      id: '/cabinet/search'
      path: '/search'
      fullPath: '/cabinet/search'
      preLoaderRoute: typeof CabinetSearchRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/encrypted': {
      id: '/cabinet/encrypted'
      path: '/encrypted'
      fullPath: '/cabinet/encrypted'
      preLoaderRoute: typeof CabinetEncryptedRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/_public/troubleshooting': {
      id: '/_public/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof PublicTroubleshootingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/cabinet/files': {
      id: '/cabinet/files'
      path: '/files'
      fullPath: '/cabinet/files'
      preLoaderRoute: typeof CabinetFilesRouteRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/docs': {
      id: '/cabinet/docs'
      path: '/docs'
      fullPath: '/cabinet/docs'
      preLoaderRoute: typeof CabinetDocsRouteRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/files/': {
      id: '/cabinet/files/'
      path: '/'
      fullPath: '/cabinet/files/'
      preLoaderRoute: typeof CabinetFilesIndexRouteImport
      parentRoute: typeof CabinetFilesRouteRoute
    }
    '/cabinet/docs/': {
      id: '/cabinet/docs/'
      path: '/'
      fullPath: '/cabinet/docs/'
      preLoaderRoute: typeof CabinetDocsIndexRouteImport
      parentRoute: typeof CabinetDocsRouteRoute
    }
    '/_public/docs/': {
      id: '/_public/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof PublicDocsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/devices/pair/request': {
      id: '/devices/pair/request'
      path: '/pair/request'
      fullPath: '/devices/pair/request'
      preLoaderRoute: typeof DevicesPairRequestRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/pair/accept': {
      id: '/devices/pair/accept'
      path: '/pair/accept'
      fullPath: '/devices/pair/accept'
      preLoaderRoute: typeof DevicesPairAcceptRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/cabinet/workspace-settings/$rkey': {
      id: '/cabinet/workspace-settings/$rkey'
      path: '/workspace-settings/$rkey'
      fullPath: '/cabinet/workspace-settings/$rkey'
      preLoaderRoute: typeof CabinetWorkspaceSettingsRkeyRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/files/$': {
      id: '/cabinet/files/$'
      path: '/$'
      fullPath: '/cabinet/files/$'
      preLoaderRoute: typeof CabinetFilesSplatRouteImport
      parentRoute: typeof CabinetFilesRouteRoute
    }
    '/cabinet/editor/new': {
      id: '/cabinet/editor/new'
      path: '/editor/new'
      fullPath: '/cabinet/editor/new'
      preLoaderRoute: typeof CabinetEditorNewRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/editor/$rkey': {
      id: '/cabinet/editor/$rkey'
      path: '/editor/$rkey'
      fullPath: '/cabinet/editor/$rkey'
      preLoaderRoute: typeof CabinetEditorRkeyRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/docs/$slug': {
      id: '/cabinet/docs/$slug'
      path: '/$slug'
      fullPath: '/cabinet/docs/$slug'
      preLoaderRoute: typeof CabinetDocsSlugRouteImport
      parentRoute: typeof CabinetDocsRouteRoute
    }
    '/_public/docs/$slug': {
      id: '/_public/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof PublicDocsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/cabinet/workspace/$rkey': {
      id: '/cabinet/workspace/$rkey'
      path: '/workspace/$rkey'
      fullPath: '/cabinet/workspace/$rkey'
      preLoaderRoute: typeof CabinetWorkspaceRkeyRouteRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/workspace/$rkey/': {
      id: '/cabinet/workspace/$rkey/'
      path: '/'
      fullPath: '/cabinet/workspace/$rkey/'
      preLoaderRoute: typeof CabinetWorkspaceRkeyIndexRouteImport
      parentRoute: typeof CabinetWorkspaceRkeyRouteRoute
    }
    '/cabinet/workspace/$rkey/$': {
      id: '/cabinet/workspace/$rkey/$'
      path: '/$'
      fullPath: '/cabinet/workspace/$rkey/$'
      preLoaderRoute: typeof CabinetWorkspaceRkeySplatRouteImport
      parentRoute: typeof CabinetWorkspaceRkeyRouteRoute
    }
    '/cabinet/workspace-editor/$rkey/new': {
      id: '/cabinet/workspace-editor/$rkey/new'
      path: '/workspace-editor/$rkey/new'
      fullPath: '/cabinet/workspace-editor/$rkey/new'
      preLoaderRoute: typeof CabinetWorkspaceEditorRkeyNewRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/workspace-editor/$rkey/$docRkey': {
      id: '/cabinet/workspace-editor/$rkey/$docRkey'
      path: '/workspace-editor/$rkey/$docRkey'
      fullPath: '/cabinet/workspace-editor/$rkey/$docRkey'
      preLoaderRoute: typeof CabinetWorkspaceEditorRkeyDocRkeyRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
  }
}

interface CabinetDocsRouteRouteChildren {
  CabinetDocsSlugRoute: typeof CabinetDocsSlugRoute
  CabinetDocsIndexRoute: typeof CabinetDocsIndexRoute
}

const CabinetDocsRouteRouteChildren: CabinetDocsRouteRouteChildren = {
  CabinetDocsSlugRoute: CabinetDocsSlugRoute,
  CabinetDocsIndexRoute: CabinetDocsIndexRoute,
}

const CabinetDocsRouteRouteWithChildren =
  CabinetDocsRouteRoute._addFileChildren(CabinetDocsRouteRouteChildren)

interface CabinetFilesRouteRouteChildren {
  CabinetFilesSplatRoute: typeof CabinetFilesSplatRoute
  CabinetFilesIndexRoute: typeof CabinetFilesIndexRoute
}

const CabinetFilesRouteRouteChildren: CabinetFilesRouteRouteChildren = {
  CabinetFilesSplatRoute: CabinetFilesSplatRoute,
  CabinetFilesIndexRoute: CabinetFilesIndexRoute,
}

const CabinetFilesRouteRouteWithChildren =
  CabinetFilesRouteRoute._addFileChildren(CabinetFilesRouteRouteChildren)

interface CabinetWorkspaceRkeyRouteRouteChildren {
  CabinetWorkspaceRkeySplatRoute: typeof CabinetWorkspaceRkeySplatRoute
  CabinetWorkspaceRkeyIndexRoute: typeof CabinetWorkspaceRkeyIndexRoute
}

const CabinetWorkspaceRkeyRouteRouteChildren: CabinetWorkspaceRkeyRouteRouteChildren =
  {
    CabinetWorkspaceRkeySplatRoute: CabinetWorkspaceRkeySplatRoute,
    CabinetWorkspaceRkeyIndexRoute: CabinetWorkspaceRkeyIndexRoute,
  }

const CabinetWorkspaceRkeyRouteRouteWithChildren =
  CabinetWorkspaceRkeyRouteRoute._addFileChildren(
    CabinetWorkspaceRkeyRouteRouteChildren,
  )

interface CabinetRouteRouteChildren {
  CabinetDocsRouteRoute: typeof CabinetDocsRouteRouteWithChildren
  CabinetFilesRouteRoute: typeof CabinetFilesRouteRouteWithChildren
  CabinetEncryptedRoute: typeof CabinetEncryptedRoute
  CabinetSearchRoute: typeof CabinetSearchRoute
  CabinetSettingsRoute: typeof CabinetSettingsRoute
  CabinetSharedRoute: typeof CabinetSharedRoute
  CabinetTasksRoute: typeof CabinetTasksRoute
  CabinetTrashRoute: typeof CabinetTrashRoute
  CabinetIndexRoute: typeof CabinetIndexRoute
  CabinetWorkspaceRkeyRouteRoute: typeof CabinetWorkspaceRkeyRouteRouteWithChildren
  CabinetEditorRkeyRoute: typeof CabinetEditorRkeyRoute
  CabinetEditorNewRoute: typeof CabinetEditorNewRoute
  CabinetWorkspaceSettingsRkeyRoute: typeof CabinetWorkspaceSettingsRkeyRoute
  CabinetWorkspaceEditorRkeyDocRkeyRoute: typeof CabinetWorkspaceEditorRkeyDocRkeyRoute
  CabinetWorkspaceEditorRkeyNewRoute: typeof CabinetWorkspaceEditorRkeyNewRoute
}

const CabinetRouteRouteChildren: CabinetRouteRouteChildren = {
  CabinetDocsRouteRoute: CabinetDocsRouteRouteWithChildren,
  CabinetFilesRouteRoute: CabinetFilesRouteRouteWithChildren,
  CabinetEncryptedRoute: CabinetEncryptedRoute,
  CabinetSearchRoute: CabinetSearchRoute,
  CabinetSettingsRoute: CabinetSettingsRoute,
  CabinetSharedRoute: CabinetSharedRoute,
  CabinetTasksRoute: CabinetTasksRoute,
  CabinetTrashRoute: CabinetTrashRoute,
  CabinetIndexRoute: CabinetIndexRoute,
  CabinetWorkspaceRkeyRouteRoute: CabinetWorkspaceRkeyRouteRouteWithChildren,
  CabinetEditorRkeyRoute: CabinetEditorRkeyRoute,
  CabinetEditorNewRoute: CabinetEditorNewRoute,
  CabinetWorkspaceSettingsRkeyRoute: CabinetWorkspaceSettingsRkeyRoute,
  CabinetWorkspaceEditorRkeyDocRkeyRoute:
    CabinetWorkspaceEditorRkeyDocRkeyRoute,
  CabinetWorkspaceEditorRkeyNewRoute: CabinetWorkspaceEditorRkeyNewRoute,
}

const CabinetRouteRouteWithChildren = CabinetRouteRoute._addFileChildren(
  CabinetRouteRouteChildren,
)

interface DevicesRouteRouteChildren {
  DevicesLoginRoute: typeof DevicesLoginRoute
  DevicesOauthCallbackRoute: typeof DevicesOauthCallbackRoute
  DevicesCliCallbackLazyRoute: typeof DevicesCliCallbackLazyRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
  DevicesPairAcceptRoute: typeof DevicesPairAcceptRoute
  DevicesPairRequestRoute: typeof DevicesPairRequestRoute
}

const DevicesRouteRouteChildren: DevicesRouteRouteChildren = {
  DevicesLoginRoute: DevicesLoginRoute,
  DevicesOauthCallbackRoute: DevicesOauthCallbackRoute,
  DevicesCliCallbackLazyRoute: DevicesCliCallbackLazyRoute,
  DevicesIndexRoute: DevicesIndexRoute,
  DevicesPairAcceptRoute: DevicesPairAcceptRoute,
  DevicesPairRequestRoute: DevicesPairRequestRoute,
}

const DevicesRouteRouteWithChildren = DevicesRouteRoute._addFileChildren(
  DevicesRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicFaqRoute: typeof PublicFaqRoute
  PublicTroubleshootingRoute: typeof PublicTroubleshootingRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDocsSlugRoute: typeof PublicDocsSlugRoute
  PublicDocsIndexRoute: typeof PublicDocsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFaqRoute: PublicFaqRoute,
  PublicTroubleshootingRoute: PublicTroubleshootingRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicDocsSlugRoute: PublicDocsSlugRoute,
  PublicDocsIndexRoute: PublicDocsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CabinetRouteRoute: CabinetRouteRouteWithChildren,
  DevicesRouteRoute: DevicesRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
