[package]
name = "opake-cli"
description = "CLI for Opake encrypted personal cloud"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "opake"
path = "src/main.rs"

[dependencies]
opake-core = { path = "../opake-core", features = ["native"] }
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
mime_guess = "2"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
urlencoding = "2"

[dev-dependencies]
opake-core = { path = "../opake-core", features = ["test-utils"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
