apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-opake-at
spec:
  secretName: staging-opake-at-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - staging.opake.at
    - indexer.staging.opake.at
