apiVersion: apps/v1
kind: Deployment
metadata:
  name: opake-indexer
spec:
  template:
    spec:
      containers:
        - name: indexer
          env:
            - name: PHX_HOST
              value: indexer.staging.opake.at
            - name: CORS_ORIGIN
              value: https://staging.opake.at
            - name: OPAKE_FRONTEND_URL
              value: https://staging.opake.at
