import type { FileItem } from "./types"

export const ROOT_ITEMS: readonly FileItem[] = [
  {
    id: "f-documents",
    name: "Documents",
    kind: "folder",
    encrypted: true,
    status: "private",
    items: 23,
    modified: "2 hours ago",
    starred: false,
  },
  {
    id: "f-projects",
    name: "Projects",
    kind: "folder",
    encrypted: true,
    status: "shared",
    sharedWith: ["alice.did", "bob.did"],
    items: 7,
    modified: "Yesterday",
    starred: true,
  },
  {
    id: "f-photos",
    name: "Photos",
    kind: "folder",
    encrypted: true,
    status: "private",
    items: 156,
    modified: "3 days ago",
    starred: false,
  },
  {
    id: "f-notes",
    name: "Notes",
    kind: "folder",
    encrypted: true,
    status: "private",
    items: 44,
    modified: "Just now",
    starred: false,
  },
  {
    id: "f-archive",
    name: "ArchiveIcon",
    kind: "folder",
    encrypted: true,
    status: "private",
    items: 12,
    modified: "1 week ago",
    starred: false,
  },
  {
    id: "fi-strategy",
    name: "Q4 Strategy.doc",
    kind: "file",
    fileType: "document",
    encrypted: true,
    status: "private",
    size: "245 KB",
    modified: "2 hours ago",
    starred: true,
  },
  {
    id: "fi-budget",
    name: "Budget 2026.xlsx",
    kind: "file",
    fileType: "spreadsheet",
    encrypted: true,
    status: "shared",
    sharedWith: ["carol.did"],
    size: "1.2 MB",
    modified: "3 days ago",
    starred: false,
  },
  {
    id: "fi-brief",
    name: "Design Brief.pdf",
    kind: "file",
    fileType: "pdf",
    encrypted: true,
    status: "private",
    size: "3.4 MB",
    modified: "Yesterday",
    starred: true,
  },
  {
    id: "fi-notes",
    name: "Team Notes.md",
    kind: "file",
    fileType: "note",
    encrypted: true,
    status: "shared",
    sharedWith: ["alice.did", "bob.did", "carol.did"],
    size: "18 KB",
    modified: "Just now",
    starred: false,
  },
  {
    id: "fi-api",
    name: "API Contracts.json",
    kind: "file",
    fileType: "code",
    encrypted: true,
    status: "private",
    size: "67 KB",
    modified: "1 week ago",
    starred: false,
  },
]

export const DOCUMENTS_ITEMS: readonly FileItem[] = [
  {
    id: "d-reports",
    name: "Reports",
    kind: "folder",
    encrypted: true,
    status: "private",
    items: 8,
    modified: "1 week ago",
    starred: false,
  },
  {
    id: "d-contracts",
    name: "Contracts",
    kind: "folder",
    encrypted: true,
    status: "shared",
    sharedWith: ["legal.did"],
    items: 5,
    modified: "2 weeks ago",
    starred: false,
  },
  {
    id: "d-thesis",
    name: "Thesis Draft v4.doc",
    kind: "file",
    fileType: "document",
    encrypted: true,
    status: "private",
    size: "1.8 MB",
    modified: "3 days ago",
    starred: true,
  },
  {
    id: "d-cv",
    name: "CV 2026.pdf",
    kind: "file",
    fileType: "pdf",
    encrypted: true,
    status: "private",
    size: "340 KB",
    modified: "1 month ago",
    starred: false,
  },
  {
    id: "d-ref",
    name: "Reference Notes.md",
    kind: "file",
    fileType: "note",
    encrypted: true,
    status: "private",
    size: "88 KB",
    modified: "5 days ago",
    starred: false,
  },
]

export const SHARED_ITEMS: readonly FileItem[] = [
  {
    id: "sh-1",
    name: "Product Roadmap.doc",
    kind: "file",
    fileType: "document",
    encrypted: true,
    status: "shared",
    sharedWith: ["team.did"],
    size: "512 KB",
    modified: "1 hour ago",
    starred: false,
  },
  {
    id: "sh-2",
    name: "Sprint Board",
    kind: "folder",
    encrypted: true,
    status: "shared",
    sharedWith: ["alice.did", "bob.did", "carol.did"],
    items: 9,
    modified: "30 min ago",
    starred: true,
  },
  {
    id: "sh-3",
    name: "Brand Assets",
    kind: "folder",
    encrypted: true,
    status: "shared",
    sharedWith: ["design.did"],
    items: 34,
    modified: "2 days ago",
    starred: false,
  },
  {
    id: "sh-4",
    name: "Meeting Notes Q1.md",
    kind: "file",
    fileType: "note",
    encrypted: true,
    status: "shared",
    sharedWith: ["alice.did"],
    size: "22 KB",
    modified: "1 week ago",
    starred: false,
  },
]
