/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as DevicesRouteRouteImport } from './routes/devices/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesIndexRouteImport } from './routes/devices/index'
import { Route as DevicesOauthCallbackRouteImport } from './routes/devices/oauth-callback'
import { Route as DevicesLoginRouteImport } from './routes/devices/login'
import { Route as DevicesCliCallbackRouteImport } from './routes/devices/cli-callback'
import { Route as DevicesPairRequestRouteImport } from './routes/devices/pair.request'
import { Route as DevicesPairAcceptRouteImport } from './routes/devices/pair.accept'

const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRouteRoute = DevicesRouteRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesOauthCallbackRoute = DevicesOauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesLoginRoute = DevicesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesCliCallbackRoute = DevicesCliCallbackRouteImport.update({
  id: '/cli-callback',
  path: '/cli-callback',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesPairRequestRoute = DevicesPairRequestRouteImport.update({
  id: '/pair/request',
  path: '/pair/request',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesPairAcceptRoute = DevicesPairAcceptRouteImport.update({
  id: '/pair/accept',
  path: '/pair/accept',
  getParentRoute: () => DevicesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRouteRouteWithChildren
  '/cabinet': typeof CabinetRoute
  '/devices/cli-callback': typeof DevicesCliCallbackRoute
  '/devices/login': typeof DevicesLoginRoute
  '/devices/oauth-callback': typeof DevicesOauthCallbackRoute
  '/devices/': typeof DevicesIndexRoute
  '/devices/pair/accept': typeof DevicesPairAcceptRoute
  '/devices/pair/request': typeof DevicesPairRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/devices/cli-callback': typeof DevicesCliCallbackRoute
  '/devices/login': typeof DevicesLoginRoute
  '/devices/oauth-callback': typeof DevicesOauthCallbackRoute
  '/devices': typeof DevicesIndexRoute
  '/devices/pair/accept': typeof DevicesPairAcceptRoute
  '/devices/pair/request': typeof DevicesPairRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRouteRouteWithChildren
  '/cabinet': typeof CabinetRoute
  '/devices/cli-callback': typeof DevicesCliCallbackRoute
  '/devices/login': typeof DevicesLoginRoute
  '/devices/oauth-callback': typeof DevicesOauthCallbackRoute
  '/devices/': typeof DevicesIndexRoute
  '/devices/pair/accept': typeof DevicesPairAcceptRoute
  '/devices/pair/request': typeof DevicesPairRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/cabinet'
    | '/devices/cli-callback'
    | '/devices/login'
    | '/devices/oauth-callback'
    | '/devices/'
    | '/devices/pair/accept'
    | '/devices/pair/request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabinet'
    | '/devices/cli-callback'
    | '/devices/login'
    | '/devices/oauth-callback'
    | '/devices'
    | '/devices/pair/accept'
    | '/devices/pair/request'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/cabinet'
    | '/devices/cli-callback'
    | '/devices/login'
    | '/devices/oauth-callback'
    | '/devices/'
    | '/devices/pair/accept'
    | '/devices/pair/request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRouteRoute: typeof DevicesRouteRouteWithChildren
  CabinetRoute: typeof CabinetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/oauth-callback': {
      id: '/devices/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/devices/oauth-callback'
      preLoaderRoute: typeof DevicesOauthCallbackRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/login': {
      id: '/devices/login'
      path: '/login'
      fullPath: '/devices/login'
      preLoaderRoute: typeof DevicesLoginRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/cli-callback': {
      id: '/devices/cli-callback'
      path: '/cli-callback'
      fullPath: '/devices/cli-callback'
      preLoaderRoute: typeof DevicesCliCallbackRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/pair/request': {
      id: '/devices/pair/request'
      path: '/pair/request'
      fullPath: '/devices/pair/request'
      preLoaderRoute: typeof DevicesPairRequestRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/pair/accept': {
      id: '/devices/pair/accept'
      path: '/pair/accept'
      fullPath: '/devices/pair/accept'
      preLoaderRoute: typeof DevicesPairAcceptRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
  }
}

interface DevicesRouteRouteChildren {
  DevicesCliCallbackRoute: typeof DevicesCliCallbackRoute
  DevicesLoginRoute: typeof DevicesLoginRoute
  DevicesOauthCallbackRoute: typeof DevicesOauthCallbackRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
  DevicesPairAcceptRoute: typeof DevicesPairAcceptRoute
  DevicesPairRequestRoute: typeof DevicesPairRequestRoute
}

const DevicesRouteRouteChildren: DevicesRouteRouteChildren = {
  DevicesCliCallbackRoute: DevicesCliCallbackRoute,
  DevicesLoginRoute: DevicesLoginRoute,
  DevicesOauthCallbackRoute: DevicesOauthCallbackRoute,
  DevicesIndexRoute: DevicesIndexRoute,
  DevicesPairAcceptRoute: DevicesPairAcceptRoute,
  DevicesPairRequestRoute: DevicesPairRequestRoute,
}

const DevicesRouteRouteWithChildren = DevicesRouteRoute._addFileChildren(
  DevicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRouteRoute: DevicesRouteRouteWithChildren,
  CabinetRoute: CabinetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
