/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCliCallbackRouteImport } from './routes/oauth.cli-callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCliCallbackRoute = OauthCliCallbackRouteImport.update({
  id: '/oauth/cli-callback',
  path: '/oauth/cli-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/login': typeof LoginRoute
  '/oauth/cli-callback': typeof OauthCliCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/login': typeof LoginRoute
  '/oauth/cli-callback': typeof OauthCliCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/login': typeof LoginRoute
  '/oauth/cli-callback': typeof OauthCliCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cabinet' | '/login' | '/oauth/cli-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabinet' | '/login' | '/oauth/cli-callback'
  id: '__root__' | '/' | '/cabinet' | '/login' | '/oauth/cli-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRoute: typeof CabinetRoute
  LoginRoute: typeof LoginRoute
  OauthCliCallbackRoute: typeof OauthCliCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/cli-callback': {
      id: '/oauth/cli-callback'
      path: '/oauth/cli-callback'
      fullPath: '/oauth/cli-callback'
      preLoaderRoute: typeof OauthCliCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRoute: CabinetRoute,
  LoginRoute: LoginRoute,
  OauthCliCallbackRoute: OauthCliCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
